SELECT CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'Payments' AND COLUMN_NAME = 'customerId'; 

ALTER TABLE Payments
DROP CONSTRAINT CONSTRAINT_NAME

ALTER TABLE Payments
DROP COLUMN currency;

ALTER TABLE Payments
ALTER COLUMN customerId VARCHAR(450) NOT NULL;

ALTER TABLE Payments
ADD CONSTRAINT FK_Payments_Customers
FOREIGN KEY (customerId) REFERENCES Customers(userId);


ALTER TABLE Payments
ALTER COLUMN paymentMethod INT;


